# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

locale: "en"
title: Path
email: wellmax111@gmail.com
description: "Fumble & Build" 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lywgit.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: /images/my-site-logo.png
read_time: true
words_per_minute: 200
mathjax: true

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

# Search
search_full_content: true

# Site Author
author:
  name: Liang-Yao Wang (王亮堯)
  picture: /images/author_lywang.jpg
  links:
    - title: GitHub
      url: https://github.com/lywgit

# Footer Links
footer_links:
  - title: GitHub
    url: https://github.com/lywgit

# Build settings
markdown: kramdown
# theme: minima
remote_theme: "mmistakes/so-simple-theme" 
plugins:
  - jekyll-feed
  - jemoji
disqus:
  shortname: https-lywgit-github-io


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
